server:
  port: 3004
  servlet:
    context-path: /write

####### resource server configuration properties
spring:
  application:
    name: write
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8080/auth/realms/my'
          jwk-set-uri: 'http://keycloak_oauth:8080/auth/realms/my/protocol/openid-connect/certs'

springdoc:
  swagger-ui:
    oauth:
      clientId: myclient
      clientSecret: JAt2LkGmYZcKKKTpQYfbOERhN7xnYpDw

####### KEYCLOAK - SWAGGER
keycloak:
  auth-server-url: 'http://localhost:8080/auth'
  realm: my   # tudo em minusculo