server:
  port: 5002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gateway1-service
          uri: http://localhost:5001
          predicates:
            - Path= /read/**, /write/**
          filters:
            - RemoveRequestHeader=Cookie
          metadata:
            cors:
              allowedOrigins: 'http://localhost:51'
              allowedMethods:
                - GET
              allowedHeaders: '*'
              maxAge: 30


